# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84edc65eb1cfc52d7edc48c60b24b7bfcb7d97c99d2af5c92067906dcb545bd207350b48d802fae78361010546c3c70ff82023554295781a483bcb61d8f7ac65

test:
  secret_key_base: f740eb3ede8cc79b24e8d4972230cd73ad87664b76e983ceb5f5984f0d8b4ba5ff8dcd8df9e58ebd1e3a6cbcabe6de0e5b3dfe41d12d77affff1864f341b47b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
